service: jobs

provider:
  name: aws
  runtime: java8
  memorySize: 1512
  timeout: 60
  stage: ${opt:stage,'dev'}
  region: ${opt:region, 'us-west-1'}
  profile: ${opt:profile, "default"}
  endpointType: REGIONAL
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "ec2:DescribeNetworkInterfaces"
          Resource: "*"
        - Effect: "Allow"
          Action: "ec2:CreateNetworkInterface"
          Resource: "*"
        - Effect: "Allow"
          Action: "ec2:DeleteNetworkInterface"
          Resource: "*"
        - Effect: "Allow"
          Action: "ec2:DescribeInstances"
          Resource: "*"
        - Effect: "Allow"
          Action: "ec2:AttachNetworkInterface"
          Resource: "*"

resources:
  Description: Jobs API

package:
  individually: true

functions:
  JobApi:
    package:
      artifact: target/devils-lake-jobs-1.0-SNAPSHOT-lambda-package.zip
    handler: personal.carlthronson.dl.be.StreamLambdaHandler::handleRequest
    events:
      - http:
          path: /{proxy+}
          method: ANY

plugins:
   - serverless-better-credentials
   - serverless-offline
